config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  get 'indices/index'
  get 'diamonds/index_mobile' => "diamonds#index_mobile"
  get 'tables/chart_second_mobile' => "tables#chart_second_mobile"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'sessions/new'

  get 'users/new'

  get 'tables/new'
  get 'lists/new'

  get 'diamonds/chart' => "diamonds#chart"

  get 'diamonds/manage_data' => "diamonds#manage_data"
  
  get 'lists/list_table' => "lists#list_table"

  get 'lists/show' => "lists#show"

  get 'tables/chart_second' => "tables#chart_second"
  
  root to: 'diamonds#index'
  
  mount Sidekiq::Web, at: '/sidekiq'
  
  post 'diamonds/run'
  
  post 'diamonds/make_list'
  
  post 'diamonds/make_index'
  
  post 'diamonds/import'
  
  get ".well-known/pki-validation/fb9df9f4770a8340de03556d4ad74f07.txt" => "diamonds#sslvalid"

  
  get 'signup',  to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/diamond.rb
class Diamond <ActiveRecord::Base

    require "date"
    

    # @weight_max = self.maximum(:weight)
    # @weight_min = self.minimum(:weight)


    
   #7days agoの日付が存在しない場合の対処

    
    scope :weight, ->(weight) {where(weight2: weight)}

    scope :color, ->(color) {where(color: color) if color.present? }
    scope :clar, ->(clar) {where(clar: clar) if clar.present? }
    scope :date, ->(date) {where(date: date) if date.present? }
    scope :cut_grade, ->(cut_grade) {where(cut_grade: cut_grade) if cut_grade.present? }
    scope :polish, ->(polish) {where(polish: polish) if polish.present?}
    scope :symmetry, ->(symmetry) {where(symmetry: symmetry) if symmetry.present? }
    scope :fluorescen, ->(fluorescen) {where(fluorescen: fluorescen) if fluorescen.present? }
    scope :certificate_id, ->(certificate_id) {where(certificate_id: certificate_id) if color.present? }
    scope :end_price, ->(end_price) {where(end_price: end_price) if end_price.present? }
    
    scope :shape, ->(shape) {where(shape: shape) if shape.present? }

    # scope :weight02, -> {where(:weight2=> @weight_min...0.3 ) }
    scope :weight02, -> {where(:weight2=> 0.01...0.3 ) }
    scope :weight03, -> {where(:weight2=> 0.3...0.4 ) }
    scope :weight04, -> {where(:weight2=> 0.4...0.5 ) }
    scope :weight05, -> {where(:weight2=> 0.5...0.6 ) }
    scope :weight06, -> {where(:weight2=> 0.6...0.7 ) }
    scope :weight07, -> {where(:weight2=> 0.7...0.8 ) }
    scope :weight08, -> {where(:weight2=> 0.8...0.9 ) }
    scope :weight09, -> {where(:weight2=> 0.9...1.0 ) }
    scope :weight10, -> {where(:weight2=> 1.0...1.2 ) }
    scope :weight12, -> {where(:weight2=> 1.2...1.5 ) }
    scope :weight15, -> {where(:weight2=> 1.5...1.8 ) }
    scope :weight18, -> {where(:weight2=> 1.8...2.0 ) }
    scope :weight20, -> {where(:weight2=> 2.0...3.0 ) }
    scope :weight30, -> {where(:weight2=> 3.0...4.0 ) }
    scope :weight40, -> {where(:weight2=> 4.0..30.0) }
    
    # Article.where("articles.title = 'Rails 3' OR articles.title = 'Rails 4'")
    scope :cut_grade_exc, -> {where("cut_grade = 'Excellent' OR cut_grade = 'EXC'" )}
    scope :cut_grade_vg, -> {where("cut_grade = 'Very Good' OR cut_grade = 'VGD'" )}
    scope :cut_grade_g, -> {where("cut_grade = 'Good' OR cut_grade = 'VGD'" )}
    
    scope :fluorescen_none, -> {where("fluorescen = 'NONE' OR fluorescen = 'None'" )}
    scope :fluorescen_faint, -> {where("fluorescen = 'Faint' OR fluorescen = 'f' OR fluorescen = 'FT'" )}
    scope :fluorescen_med, -> {where("fluorescen = 'Medium' OR fluorescen = 'mb' OR fluorescen = 'Medium Blue' OR fluorescen = 'md blue' OR fluorescen = 'M.BLUE'" )}
    scope :fluorescen_strong, -> {where("fluorescen = 'Strong' OR fluorescen = 'st' OR fluorescen = 'sb' OR fluorescen = 'str blue' OR fluorescen = 'S.BLUE'" )}
    scope :fluorescen_vs, -> {where("fluorescen = 'VST' OR fluorescen = 'Very Strong' OR fluorescen = 'V.S.BLUE'" )}
    

  def self.import(file)
  # CSV.foreach(file.path, headers: true, encoding:'iso-8859-1:utf-8') do |row|
  # Diamond.create(:date => row[0], :weight => row[4], :color => row[5], :clar => row[9], :length => row[10], :width => row[11],
  #               :depth => row[12], :cut_grade => row[14], :rapnet_list_price => row[16], :rapnet_discount => row[17], :price_per_carat => row[18], 
  #               :polish => row[26], :symmetry => row[27], :fluorescen => row[28], :certificate_id => row[37], :end_price => row[48])
  #   end
  end
  
  def task(file)
  end
  

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["date", "weight2", "color", "clar", "cut_grade", "rapnet_list_price", "rapnet_discount", 
     "price_per_carat", "polish", "symmetry", "fluorescen", "certificate_id", "end_price"]
  end
    
    
    
    
end

app/controllers/diamonds_controller.rb
class DiamondsController < ApplicationController
  before_action :require_user, except: [:index, :chart, :index_mobile, :sslvalid]
  
  #http://申請したFQDN/.well-known/pki-validation/fileauth.txt 
  def sslvalid
    render text: "5c1d8520b6f33107ff0099849e8c951c"
  end
  
  def new
    @diamond = Diamond.new
  end

  def group_color(weight, color)
    "@weight" + weight + "_diamond_group.weight" + weight + ".color(" + "\"" + color + "\"" + ")"
  end
  
  def run
    OrganizeDiamondsJob.perform_later
    #EventWorker.perform_async
    redirect_to root_url, notice: "チャート用データ作成を開始しました。"
  end
  
  def make_list
    OrganizeListsJob.perform_later
    #EventWorker.perform_async
    redirect_to root_url, notice: "Daily価格テーブル作成を開始しました。"
  end
  
  def make_index
    OrganizeIndexJob.perform_later
    redirect_to root_url, notice: "Indexテーブル作成を開始しました。"
  end

  def import
    redirect_to root_url, notice: "Diamondデータの追加を開始しました。"
    @file = params[:file].path
    options = {:col_sep => ',', :row_sep => :auto, :remove_empty_values => false,
    :remove_empty_hashes => false, :file_encoding  => 'iso-8859-1'}
      SmarterCSV.process(@file, options) do |chunk|
        CsvImportJob.perform_later(chunk)
      end
    
  end
  
  require "date"
  def index
   
   
    # @diamonds = Diamond.all
    #kaminariでページネーション
    # @diamonds = Diamond.page(params[:page])
    @q = Diamond.ransack(params[:q])
    # @diamonds2 = @q.result(distinct: true)
   
   @weight = ["02", "03", "04", "05", "06", "07", "08", "09", "10", "12", "15", "18", "20", "30", "40"]
   @color = ["D", "E", "F", "G", "H", "I", "J", "K", "L", "M"]
   @clar = ["IF", "VVS1", "VVS2", "VS1", "VS2", "SI1", "SI2"]
  # @cut_grade = ["Good", "Very Good", "Excellent", "EXC", "VGD", "F"]
   @cut_grade = ["Good", "Very Good", "VGD", "Excellent", "EXC"]
   @polish = ["Excellent", "Very Good", "ex", "vg", "vgd", "gd", "exc", "Good"]
   @symmetry = ["Excellent", "Very Good", "ex", "vg", "vgd", "gd", "exc", "Good", "g", "Fair", "F"]
  # @fluorescen = ["Medium", "Faint", "None", "Strong", "f", "mb", "NONE", "Medium Blue", "md blue", 
  #               "st", "sb", "str blue", "S.BLUE", "M.BLUE", "VST", "Very Strong", "V.S.BLUE", "FT"]
   @fluorescen = ["Medium", "Faint", "f", "FT", "None", "NONE", "Strong", "st", "Medium Blue", "M.BLUE", "mb", "md blue", "str blue", "sb", "S.BLUE", "Very Strong", "VST", "V.S.BLUE"]
   

   #最新旧の日付を取得
  @latest_date = Table.maximum(:date)
  @oldest_date = Table.minimum(:date)
  if @latest_date.present?
    @one_week_ago = @latest_date - 6
  end
  
  @ref_date = Date.new(2015, 1, 1)
  
  # if @latest_date.present?
  #     if @latest_date <= Date.new(2015, 12, 31)
  #       @ref_date = Date.new(2015, 1, 1)
  #     elsif @latest_date >= Date.new(2016, 1, 1) and @latest_date <= Date.new(2016, 12, 31)
  #       @ref_date = Date.new(2016, 1, 1)
  #     elsif @latest_date >= Date.new(2017, 1, 1) and @latest_date <= Date.new(2017, 12, 31)
  #       @ref_date = Date.new(2017, 1, 1)
  #     elsif @latest_date >= Date.new(2018, 1, 1) and @latest_date <= Date.new(2018, 12, 31)
  #       @ref_date = Date.new(2018, 1, 1)
  #     end
  # end
  

    
    # binding.pry
    #配列からWhileでloop
    # i = 0
    # while i < ary.length
    #   print ary[i]
    #   i += 1
    # end

   @latest_weight_group_03 = List.select('color, if1, vvs1, vvs2, vs1, vs2, si1, si2').where(weight2: 0.3).where(date: @latest_date)
   
  # @latest_chart_table_weight_group_03 = Table.select('date, color, clar, price').where(weight2: 0.3).group(:date, :color, :clar)
  # @latest_one_week_data = Table.select('date, weight, color, clar, price').where(:date=> @one_week_ago..@latest_date).group(:date, :weight2, :color, :clar)
  # weight_group_03_color_D_IF = @latest_one_week_data.where(weight2: 0.3).where(color: "D").where(clar: "IF")
   
   @latest_chart_index_group = Index.select('date, index1').group(:date)
   @latest_one_year_data = Index.select('date, index1').where(:date=> @ref_date..@latest_date).group(:date)

   
    #0.3_All
    #Date
    # weight_group_03_color_D_IF_date = weight_group_03_color_D_IF.pluck(:date)
    # weight_group_03_color_D_IF_end_price = weight_group_03_color_D_IF.pluck(:price)
    
    # time.strftime('%Y-%m-%d %H:%M:%S')
    
    one_year_group_date_raw = @latest_one_year_data.pluck(:date)
    one_year_group_date = one_year_group_date_raw.map {|date| date.to_datetime.utc.to_i*1000}
       
      # Time.utc(2011,01,01).to_i * 1000
       
      # one_year_group_date =[]
      # d = 0
      # while d < one_year_group_date_raw.length
      #   date = one_year_group_date_raw[d]
      #   # date_format = date.to_datetime.strftime('%Y,%m,%d')
      #   # date_format2 =Time.utc(date_format).to_1*1000
      #   # one_year_group_date << date_format2
      #   one_year_group_date << date.to_datetime.utc.to_i*1000
      #   # one_year_group_date << date.to_datetime.to_i
      #   # one_year_group_date << date.to_datetime.strftime('%Y-%m-%d %H:%M:%S')
      #   # one_year_group_date << date.to_datetime.strftime('%m %d %Y %H:%M')
      #   # one_year_group_date << date.to_datetime.strftime('%Y-%m-%d')
      #   # one_year_group_date << date.to_date.utc
      #   d += 1
      # end
     
    
    
    one_year_group_date_index1 = @latest_one_year_data.pluck(:index1)
    one_year_group_date_index2 = @latest_one_year_data.pluck(:index2)
    one_year_group_date_index3 = @latest_one_year_data.pluck(:index3)
    one_year_group_date_index4 = @latest_one_year_data.pluck(:index4)
    
    @zip_data_index1 = one_year_group_date.zip(one_year_group_date_index1)
    @zip_data_index2 = one_year_group_date.zip(one_year_group_date_index2)
    @zip_data_index3 = one_year_group_date.zip(one_year_group_date_index3)
    @zip_data_index4 = one_year_group_date.zip(one_year_group_date_index4)

    # binding.pry
    
    
    @chart = LazyHighCharts::HighChart.new('graph') do |f|
      
      f.global(useUTC: false)
      @sdate = one_year_group_date.find.first
      @date = one_year_group_date
      # f.title(:text => "指標")
      
      # f.xAxis(:type => 'datetime', :title => { text: 'Date'})
      f.xAxis(:type => 'datetime', :dateTimeLabelFormats => {day: '%e. %b', month: '%b' }, :title => { text: 'Date'})
      # f.xAxis(:type => 'datetime', :dateTimeLabelFormats => {second: '%l:%M:%S %p',
      #                         minute: '%l:%M %p', 
      #                         hour: '%l:%M %p',
      #                         day: '%e. %b', week: '%e. %b', 
      #                         month: '%b \'%y', year: '%Y'}, :title => { text: 'Date'})
      # f.xAxis(:type => 'datetime', :dateTimeLabelFormats => { month: '%e of %b'}, :title => { text: 'Date'})
      # f.tooltip(:headerFormat => '<b>{series.name}</b><br>', :pointFormat => '{point.x:%e. %b}: {point.y:.2f} m')
      # f.xAxis(:categories => @date)
      f.yAxis(:title => { text: 'Index(%)' })
      
      # f.xAxis(:categories => weight_group_03_color_D_IF_date)
      # f.series(:pointInterval => 1.day, :pointStart => @sdate, :name => "0.3_D_IF", :data => weight_group_03_color_D_IF_end_price)
      # f.series(:name => "0.3_D_IF", :data => one_year_group_date_index1)
      # f.series(:name => "Index", :data => one_year_group_date_index1)
      
      f.series(:name => "ダイヤモンドIndex", :data => @zip_data_index4, :marker => {enabled: false})
      f.series(:name => "ダイヤモンド単価Index", :data => @zip_data_index1, :marker => {enabled: false})

      
      # f.series(:name => "JPIndex", :data => @zip_data_index3)
      
      
      # f.series(:pointInterval => 1.day, :pointStart => @sdate, :name => "0.3_D_VVS1", :data => weight_group_03_color_D_VVS1_end_price)

      
      # f.legend(:align => 'right', :verticalAlign => 'top', :y => 0, :x => -50, :layout => 'vertical',)
      f.legend(:align => 'left', :floating => true, :verticalAlign => 'top', :y =>2, :x => 90, :layout => 'vertical',)
      # f.chart(type: 'line', height: 600, width: 980)
      f.chart(type: 'line', height: 500)
      # f.chart(type: 'line')
      # f.chart({:defaultSeriesType=>"column"})
    end

  end
  
  
  def manage_data
    
    # OrganizeDiamondsJob.perform_later
    # OrganizeDiamondsJob.perform
    # EventWorker.perform_async
    
  end
  

  def create
    @diamond = Diamond.new(diamond_params)
    @diamond.save
    redirect_to root_path , notice: 'データを保存しました'
  end
  
  
  #mobile page------------------------------------------------------------------------------
  def index_mobile
    # render :layout => 'mobile_page'
   
    @q = Diamond.ransack(params[:q])
    @diamonds2 = @q.result(distinct: true)
   
   @weight = ["02", "03", "04", "05", "06", "07", "08", "09", "10", "12", "15", "18", "20", "30", "40"]
   @color = ["D", "E", "F", "G", "H", "I", "J", "K", "L", "M"]
   @clar = ["IF", "VVS1", "VVS2", "VS1", "VS2", "SI1", "SI2"]
   @cut_grade = ["Good", "Very Good", "VGD", "Excellent", "EXC"]
   @polish = ["Excellent", "Very Good", "ex", "vg", "vgd", "gd", "exc", "Good"]
   @symmetry = ["Excellent", "Very Good", "ex", "vg", "vgd", "gd", "exc", "Good", "g", "Fair", "F"]
   @fluorescen = ["Medium", "Faint", "f", "FT", "None", "NONE", "Strong", "st", "Medium Blue", "M.BLUE", "mb", "md blue", "str blue", "sb", "S.BLUE", "Very Strong", "VST", "V.S.BLUE"]
   

   #最新旧の日付を取得
  @latest_date = Table.maximum(:date)
  @oldest_date = Table.minimum(:date)
  if @latest_date.present?
    @one_week_ago = @latest_date - 6
  end
  
  @ref_date = Date.new(2015, 1, 1)
   @latest_weight_group_03 = List.select('color, if1, vvs1, vvs2, vs1, vs2, si1, si2').where(weight2: 0.3).where(date: @latest_date)
   @latest_chart_index_group = Index.select('date, index1').group(:date)
   @latest_one_year_data = Index.select('date, index1').where(:date=> @ref_date..@latest_date).group(:date)

    
    one_year_group_date_raw = @latest_one_year_data.pluck(:date)
    one_year_group_date = one_year_group_date_raw.map {|date| date.to_datetime.utc.to_i*1000}

app/helpers/diamonds_helper.rb
module DiamondsHelper
end

app/views/diamonds/_chart_form.html.erb
<div class="container center">
    <h3 class="user_margin_1">チャートをカスタマイズして表示</h3>

    <%= search_form_for(@q, url: diamonds_chart_path, method: :get) do |f| %>
        <div class="use_margin_2">
            <%= f.label :date, "表示期間:" %>
            <%= f.select :date, {"2週間" => "2w", "1ヶ月" => "1m", "3ヶ月" => "3m", 
                                    "6ヶ月" => "6m", "1年" => "1y", "最大" => "max"} %>
            &nbsp;
            <%= f.label :weight, "カラット:" %>
            <%= f.select :weight2, {"0.3" => 0.3, "0.4" => 0.4, "0.5" => 0.5, "0.6" => 0.6,
                                 "0.7" => 0.7, "0.8" => 0.8, "0.9" => 0.9, "1.0" => 1, 
                                 "1.2" =>  1.2, "1.5" => 1.5} %>
            &nbsp;
            <%= f.label :color, "カラー:" %>
            <%= f.select :color, {"全て" => "all", "D" => "D", "E" => "E", "F" => "F", "G" => "G",
                                 "H" => "H", "I" => "I", "J" => "J", "K" => "K", 
                                 "L" => "L", "M" => "M"} %>
            &nbsp;
            <%= f.label :clar, "クラリティ:" %>
            <%= f.select :clar, {"全て" => "all", "IF" => "IF", "VVS1" => "VVS1", "VVS2" => "VVS2",
                                 "VS1" => "VS1", "VS2" => "VS2", "SI1" => "SI1", "SI2" => "SI2"} %>
            &nbsp;&nbsp;
            <%= f.submit "チャートを表示" %>
        </div>
    <% end %>
</div>

app/views/diamonds/_diamond_chart.html.erb
<div class="container user_margin2">
	<div id="diamonds-chart" >
        <%= high_chart("diamonds-chart", @chart) %>
    </div>
</div>

app/views/diamonds/_diamond_chart_mobile.erb
<div class="container user_margin2">
	<div id="diamonds-chart" >
        <%= high_chart("diamonds-chart", @chart_mobile) %>
    </div>
</div>

app/views/diamonds/_diamond_market.html.erb
<div class="container user_margin2">
	
	<p>0.3カラット_<%=@latest_date %></p>
	<table class="table table-bordered">
      <tr>
        <th bgcolor = "E7F1ED"><div class="text-center">Color</div></th>
        <th bgcolor = "E7F1ED"><div class="text-center">IF</div></th>
        <th bgcolor = "E7F1ED"><div class="text-center">VVS1</div></th>
        <th bgcolor = "E7F1ED"><div class="text-center">VVs2</div></th>
        <th bgcolor = "E7F1ED"><div class="text-center">VS1</div></th>
        <th bgcolor = "E7F1ED"><div class="text-center">VS2</div></th>
        <th bgcolor = "E7F1ED"><div class="text-center">SI1</div></th>
        <th bgcolor = "E7F1ED"><div class="text-center">SI2</div></th>
      </tr>
    
       <% @latest_weight_group_03.each do |diamond| %>
          <tr>
            <td bgcolor = "E7F1ED" align="center"><%= diamond.color %></td>
            <td align="center"><%= diamond.if1 %></td>
            <td align="center"><%= diamond.vvs1 %></td>
            <td align="center"><%= diamond.vvs2 %></td>
            <td align="center"><%= diamond.vs1 %></td>
            <td align="center"><%= diamond.vs2 %></td>
            <td align="center"><%= diamond.si1 %></td>
            <td align="center"><%= diamond.si2 %></td>
          </tr>
      <% end %>
  </table>




</div>

app/views/diamonds/_diamond_price_history.html.erb
<div class="container user_width_1">
  <p>Diammond相場価格(0.3カラット Latest one week)</p>
	<table class="table table-bordered user_table">
      <tr>
        <th bgcolor = "E7F1ED"><div class="text-center">Date</div></th>
        <th bgcolor = "E7F1ED"><div class="text-center">Color</div></th>
        <th bgcolor = "E7F1ED"><div class="text-center">Clarity</div></th>
        <th bgcolor = "E7F1ED"><div class="text-center">Price</div></th>
      </tr>
      <% @daily_weight_group_03_color_D_IF.each do |diamond| %>
        <tr>
          <td bgcolor = "E7F1ED" align="center"><%= diamond.date %></td>
          <td align="center"><%= diamond.color %></td>
          <td align="center"><%= diamond.clar %></td>
          <td align="center"><%= diamond.avg_price.round %></td>
        </tr>
      <% end %>
    </table>
</div>

app/views/diamonds/chart.html.erb
<h1>ダイヤモンド相場価格トレンド</h1>

    <div id="diamonds-chart">
        <%= high_chart("diamonds-chart", @chart) %>
    </div>
    
    <%= render 'chart_form' %>  

app/views/diamonds/index.html.erb
<h1>ダイヤモンドインデックス</h1>

<div class="container">
	<!--<h3>価格チャート <span class="label label-default">0.3カラット</span></h3>-->
	<!--<p>-->
	<!--<%= link_to "価格チャート", tables_chart_second_path, class: "btn btn-primary btn-lg" %>-->
	<!--</p>-->
	<%= render 'diamond_chart' %>
	
	<!--<#%= line_chart Index.group(:date).maximum(:index1) %>-->
	
	<!--<h3 class="user_margin1">相場価格 <span class="label label-default">0.3カラット-<%= @latest_date %></span></h3>-->
	<!--<p>-->
	<!--<%= link_to "相場価格指標", lists_show_path, class: "btn btn-primary btn-lg" %>-->
	<!--</p>-->
	<!--<#%= render 'diamond_market' %>-->



</div>

app/views/diamonds/index_mobile.erb
<h2>ダイヤモンドインデックス</h2>

<div class="container">

	<%= render 'diamond_chart_mobile' %>
	

</div>

app/views/diamonds/manage_data.html.erb
<h1>Data management page</h1>

<div class= "container">
	<%= form_tag diamonds_import_path, multipart: true do %>
		<%= file_field_tag :file %>
		<%= submit_tag "CSVファイルインポート", :class => "btn btn-primary btn-lg btn-block user_margin1 user_padding1" %>
    <% end %>
    
    <%= button_to "チャート用データテーブル作成", { :action => "run"}, :class => "btn btn-primary btn-lg btn-block user_margin1 user_padding1" %>
    
    <%= button_to "Daily価格テーブル作成", { :action => "make_list"}, :class => "btn btn-primary btn-lg btn-block user_margin1 user_padding1" %>
    
    <%= button_to "Indexテーブル作成", { :action => "make_index"}, :class => "btn btn-primary btn-lg btn-block user_margin1 user_padding1" %>
    
    <div>
        <btn><%= link_to "Admin管理ページ", admin_root_path, :class => "btn btn-primary btn-lg user_margin1" %></btn>
    </div>
    
</div>

app/views/diamonds/new.html.erb
<h1>Diamonds#new</h1>
<p>Find me in app/views/diamonds/new.html.erb</p>