config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  get 'indices/index'
  get 'diamonds/index_mobile' => "diamonds#index_mobile"
  get 'tables/chart_second_mobile' => "tables#chart_second_mobile"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'sessions/new'

  get 'users/new'

  get 'tables/new'
  get 'lists/new'

  get 'diamonds/chart' => "diamonds#chart"

  get 'diamonds/manage_data' => "diamonds#manage_data"
  
  get 'lists/list_table' => "lists#list_table"

  get 'lists/show' => "lists#show"

  get 'tables/chart_second' => "tables#chart_second"
  
  root to: 'diamonds#index'
  
  mount Sidekiq::Web, at: '/sidekiq'
  
  post 'diamonds/run'
  
  post 'diamonds/make_list'
  
  post 'diamonds/make_index'
  
  post 'diamonds/import'
  
  get ".well-known/pki-validation/fb9df9f4770a8340de03556d4ad74f07.txt" => "diamonds#sslvalid"

  
  get 'signup',  to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

end

app/views/layouts/_header.html.erb
<header>
    <div class="container">
        <nav>
          <ul id="chart_menu" class="nav nav-tabs">
                <li role="presentation"><%= link_to "ダイヤモンドインデックス", root_path %></li>
                <li role="presentation"><%= link_to "ダイヤモンドチャート", tables_chart_second_path %></li>
                <li role="presentation"><%= link_to "ダイヤモンド価格表", lists_show_path %></li>
          </ul>
          
          <ul class="nav navbar-nav navbar-right">  
            <% if logged_in? %>
              <% if current_user.id == 1 || current_user.id == 2 %>
                <li class="hidden-xs"><%= link_to "データ管理", diamonds_manage_data_path %></li>
                <li class="hidden-xs"><%= link_to "Log out", logout_path, method: "delete" %></l1>
              <% else %>
                <li class="hidden-xs">
                <%= link_to "Log out", logout_path, method: "delete" %>
                </li>
              <% end %>
            <% else %>
            <li class="hidden-xs"><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
    
    </div>
</header>

app/views/layouts/_header_mobile.html.erb
<header>
    <div class="container">
        <h2>Mobile page-test</h2>
    
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diamond Data</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
    	  <%= render 'layouts/header' %>  
    	  <% flash.each do |message_type, message| %> 
     	　  <div class="alert alert-<%= message_type %>"><%= message %></div>
     	  <% end %>
        <%= yield %>
    </div>

</body>
</html>

app/views/layouts/mobile_page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Diamond Data</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
        <%= render 'layouts/header_mobile' %>  
        <%= yield %>
    </div>

</body>
</html>